# Generated by Django 4.2.10 on 2025-11-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zonas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('rol', models.CharField(blank=True, choices=[('guardia_seguridad', 'Guardia de Seguridad'), ('jefe_seguridad', 'Jefe de Seguridad')], help_text='Rol del usuario: guardia_seguridad (patrulla) o jefe_seguridad (supervisa todo). Asignado automáticamente al crear.', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='VinculacionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('dispositivo_id', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
            options={
                'verbose_name': 'Vinculación de Dispositivo',
                'verbose_name_plural': 'Vinculaciones de Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Sesion_del_Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
            options={
                'verbose_name': 'Sesión del Perfil',
                'verbose_name_plural': 'Sesiones de Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.categoria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
            options={
                'verbose_name': 'Perfil-Categoría',
                'verbose_name_plural': 'Perfiles-Categorías',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='categorias',
            field=models.ManyToManyField(blank=True, help_text='Categorías/turnos asignados al perfil.', related_name='perfiles', through='perfil.Perfil_Categoria', to='perfil.categoria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona asignada al guardia. Jefes de seguridad no requieren zona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='zonas.zona'),
        ),
    ]
